# Generated by Django 6.0.7 on 2026-09-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubchanges',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clubchanges',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='clubchanges',
            name='submitted_by',
        ),
        migrations.RemoveConstraint(
            model_name='clubmembership',
            name='unique_club_membership',
        ),
        migrations.DeleteModel(
            name='ClubChanges',
        ),
        migrations.DeleteModel(
            name='ClubMembership',
        ),
    ]
