# Generated by Django 6.0.7 on 2026-09-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_custom_club_memberships'),
        ('clubs', '0007_remove_clubannouncement_pinned_and_more'),
    ]

    operations = [
    ]
