# Generated by Django 6.0.7 on 2026-09-06 16:54

import colorfield.fields
import django.db.models.deletion
import image_cropping.fields
import management.models
import osm_field.fields
import osm_field.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_site_name', models.CharField(choices=[('HM', 'Home'), ('CL', 'Clubs'), ('GL', 'Gallery'), ('AB', 'About')], max_length=2)),
                ('title', models.CharField(help_text='This is the title of the page. It is the TOP of the title section.', max_length=30)),
                ('subtitle', models.CharField(blank=True, help_text='This is the subtitle of the page. It is the BOTTOM of the title section (secondary color). *NOT REQUIRED', max_length=30)),
                ('tagline', models.TextField(blank=True, help_text='This is the bullet points of the title. It should be short and tells the user a bit about the page. *NOT REQUIRED', max_length=200)),
            ],
            options={
                'verbose_name': 'Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainance_mode', models.BooleanField(default=False)),
                ('frontend_url', models.URLField(default='http://localhost:3000', help_text='The external url of frontend', max_length=100)),
                ('school_name', models.CharField(default='SCHOOL', help_text='The name of the school *Use short form S.S (e.g, Richmond Green S.S)', max_length=40)),
                ('council_name', models.CharField(default='STUCO', help_text='The name of the council (e.g, SAC)', max_length=10)),
                ('school_email', models.EmailField(blank=True, max_length=50)),
                ('school_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('favicon', models.ImageField(blank=True, help_text='This is the icon that appears in the browser tab. It should be a square image, preferably 32x32 pixels.', upload_to=management.models.FaviconRename)),
                ('favicon_cropping', image_cropping.fields.ImageRatioField('favicon', '32x32', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The small icon next to the browser tab title. Save new uploaded image then re-open this page to view your new uploaded photo.', hide_image_field=False, size_warning=False, verbose_name='favicon cropping')),
                ('site_logo', models.ImageField(blank=True, help_text='This is the icon that represents your school', upload_to=management.models.SiteLogoRename)),
                ('site_logo_cropping', image_cropping.fields.ImageRatioField('site_logo', '80x80', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text='Save new uploaded image then re-open this page to view your new uploaded photo.', hide_image_field=False, size_warning=False, verbose_name='site logo cropping')),
                ('school_mascot', models.CharField(blank=True, help_text="This is the school's mascot. (e.g, Wildcat, Rattler) *Non-plural*.", max_length=50)),
                ('school_primary_color', colorfield.fields.ColorField(default='#000000', help_text='This is the primary color of the school. It should be a hex code (e.g., #FF0000).', image_field=None, max_length=25, samples=None)),
                ('school_secondary_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='This is the secondary color of the school. It should be a hex code (e.g., #000000).', image_field=None, max_length=25, samples=None)),
                ('school_tertiary_color', colorfield.fields.ColorField(default='#FF0000', help_text="This is the 'accent' color of the site. It should be a hex code (e.g., #FFFFFF).", image_field=None, max_length=25, samples=None)),
                ('captcha', models.JSONField(blank=True, default=list)),
                ('school_domain', models.CharField(help_text='This is the domain of the school. e.g yrdsb.ca, tdsb.on.ca, etc. This is used for email verification', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', osm_field.fields.LatitudeField(null=True, validators=[osm_field.validators.validate_latitude])),
                ('location_lon', osm_field.fields.LongitudeField(null=True, validators=[osm_field.validators.validate_longitude])),
                ('location', osm_field.fields.OSMField(help_text="Click on the map of the school's location. You can also search for it in the search bar.", lat_field='location_lat', lon_field='location_lon', null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('IG', 'Instagram'), ('YT', 'YouTube'), ('LI', 'LinkedIn'), ('OT', 'Other')], max_length=2, null=True)),
                ('title', models.CharField(blank=True, help_text='This is needed only to override the default site title', max_length=20, null=True)),
                ('link', models.URLField(max_length=500, null=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_media', to='management.sitesettings')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
    ]
